name: CI

on: 
  push:
    branches:
      - master
    pull_request:

jobs:
  ci:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    
    - name: Install Poetry
      run: pip install poetry=="1.1.11"
    
    - name: Config poetry
      run: poetry config virtualenvs.in-project true    
    
    - name: Install Dependencies
      run: poetry install

    - name: Code Style
      run: |
        poetry run black . --check
        poetry run pylint ./appexemple
        poetry run isort . --check
    - name: Test & Coverage
      run: |
        poetry run pytest --cov-report term  --cov-report xml:coverage.xml --cov=inupdater
    - name: "Upload coverage to Codecov"
      uses: codecov/codecov-action@v1
      with:
        fail_ci_if_error: truepytest --cov-
      
    - name: Docs
      run: |:
        git config user.name 'github-actions[bot]'
        git config user.email 'github-actions[bot]@users.noreply.github.com'
        poetry run mkdocs gh-deploy --force

    - name: Re-Build Resource
      run: poetry run pyside6-rcc resource.qrc -o src/inupdater/resource.py

    - name: Check for uncommitted changes
      id: check-changes
      uses: mskri/check-uncommitted-changes-action@v1.0.1
    - name: Evaluate if there are changes
      if: steps.check-changes.outputs.outcome == failure()
        run: echo "Please rebuild ressource  with 'pyside6-rcc resource.qrc -o src/inupdater/resource.py'"

    - name: Build Exe
      run: poetry run pyinstaller --clean --onefile --noconsole --name launcher --paths .venv/Lib/site-packages --exclude-module _bootlocale --paths .venv/Scripts src/inupdater/__main__.py
    - uses: actions/upload-artifact@v2
      with:
        name: launcher
        path: dist/
