name: release

on:
  push:
    tags:
      - "*.*.*"

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
    
      - name: Install Poetry
        run: pip install poetry=="1.1.6"
      
      - name: Config poetry
        run: poetry config virtualenvs.in-project true    
    
      - name: Install Dependencies
        run: poetry install

      - name: Re-Build Resource
        run: poetry run pyside6-rcc resource.qrc -o src/inupdater/resource.py

      # TODO : Find an equivalent on windows
      # - name: Check for uncommitted changes
      #   id: check-changes
      #   uses: mskri/check-uncommitted-changes-action@v1.0.1
      # - name: Evaluate if there are changes
      #   if: steps.check-changes.outputs.outcome == failure()
      #   run: echo "Please rebuild ressource  with 'pyside6-rcc resource.qrc -o src/inupdater/resource.py'"
      
      - name: Build
        run: poetry run pyinstaller --clean --onefile --noconsole --name launcher --paths .venv/Lib/site-packages --exclude-module _bootlocale --paths .venv/Scripts src/inupdater/__main__.py
      
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist\launcher.exe
